name: "Contributor License Agreement Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "Contributor License Agreement Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA. If applicable, I have obtained all necessary approvals from my employer to make this contribution under the terms of the CLA.') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PERSONAL_ACCESS_TOKEN }}
        with:
          custom-pr-sign-comment: "I have read the CLA Document and I hereby sign the CLA. If applicable, I have obtained all necessary approvals from my employer to make this contribution under the terms of the CLA."
          path-to-document: "https://github.com/saulova/ts-dipend/blob/main/CLA.md"
          branch: "main"
          allowlist: saulova,dependabot[bot]
          remote-organization-name: saulova
          remote-repository-name: dipend-cla
          path-to-signatures: "cla-signatures.json"
